config/routes.rb
Rails.application.routes.draw do
  

  

  resources :users, only: [:index, :edit, :update]
  get 'recipient' => "users#recipient"
  patch 'update_recipient' => "users#update_recipient"
  
  resources :categories
  
  devise_for :users
  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create]
    resources :reviews, except: [:show, :index]
  end
  get 'orders/:id' => "orders#receipt", as: :receipt
  get 'pages/about'

  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  
  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  if Rails.env.development?
    has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg"
  else
    has_attached_file :image, :styles => { :medium => "200x", :thumb => "100x100>" }, :default_url => "default.jpg",
        :storage => :dropbox,
        :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
        :path => ":style/:id_:filename"
  end

  validates :name, :description, :price, :category_id, presence: true
  validates :price, numericality: { greater_than: 0 }
#  validates_attachment_presence :image
  validates :qty_in_stock, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    message: "can only be positive greater than 0"
  }
  validates_attachment_content_type :image, :content_type => /\Aimage/
  
  belongs_to :user
  belongs_to :category
  has_many :orders
  has_many :reviews
  
  searchkick
  
  scope :active, -> { where(published: true) }
  scope :inactive, -> { where(published: false)}
  scope :recent, -> { order(created_at: :desc) }
  scope :by_logged_user, -> (logged_user) { where(user: logged_user)}
  scope :by_category, -> (category) { where(category_id: category) }
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
   
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]
  
  def search
    if params[:search].present?
      @listings = Listing.search params[:search], where: {published: true}, page: params[:page], per_page: Paginable::LISTING_INDEX_MAX_PER_PAGE
    else
      @listings = Listing.active.recent.paginate(pagination_size(Paginable::LISTING_INDEX_MAX_PER_PAGE))
    end 
  end
  
  def seller
    @listings = Listing.by_logged_user(current_user).recent.paginate(pagination_size(Paginable::LISTING_SELLER_MAX_PER_PAGE))
  end
  
  # GET /listings
  # GET /listings.json
  def index
    if params[:category].blank?
      @listings = Listing.active.recent.paginate(pagination_size(Paginable::LISTING_INDEX_MAX_PER_PAGE))
    else
      category_id = Category.find_by_category(params[:category]).id
      @listings = Listing.by_category(category_id).active.recent.paginate(pagination_size(Paginable::LISTING_INDEX_MAX_PER_PAGE))
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @reviews = Review.by_listing(@listing.id).recent
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
 
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully removed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
      @listing_decorator = ListingDecorator.new(@listing)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :category_id, :description, :price, :qty_in_stock, :image, :published)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing product belongs to someone else"
      end
    end
  
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => { :multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.active.sorted, :id, :category, {prompt: "Choose a category"}, class: "btn btn-default dropdown-toggle" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :quantity_in_stock %><br>
    <%= f.text_field :qty_in_stock, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :published %> <%= f.label "Published" %>
  </div>
<!--
<% if current_user.recipient.blank? %>
  <br>
  <h1>Bank Account Information</h1>

  <div class="form-group">
    <%= label_tag :country %>
    <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= label_tag :routing_number %>
    <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= label_tag :account_number %>
    <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
  </div>
<% end %>
-->
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>            
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Edit listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>Handcrafted items from <br/> around the world.</h1>
  <h2>Discover one-of-a-kind items</h2>
</div>

<div class="center">
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>
        <div class="caption">
          <h4><strong><%= listing.name %></strong></h4>
          <p><%= number_to_currency(listing.price) %></p>
          Sold by <strong><%= "#{listing.user.name}" %></strong>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>  
<br/>
<div class="center">
  <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</div>
<br/>
<% if user_signed_in? %>
<%= link_to new_listing_path, class: "btn btn-primary active", data: { no_turbolink: true } do %>
    <i class="glyphicon glyphicon-plus"></i> New Listing
  <% end %>
<% end %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/search.html.erb
<div class="center">
<div class="row">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>
        <div class="caption">
          <h3><strong><%= listing.name %></strong></h3>
          <p><%= number_to_currency(listing.price) %></p>
          <p><%= "Sold by #{listing.user.name}" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>  
<br/>
<div class="center">
  <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</div>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>
<br/>

<div class="center">
  <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</div>

<br>
<% if user_signed_in? %>
  <%= link_to new_listing_path, class: "btn btn-primary", data: { no_turbolink: true } do %>
    <i class="glyphicon glyphicon-plus"></i> New Listing
  <% end %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @listing_decorator.image.url %>
    </div>
  </div>
  <div class="col-md-6">
    <h4><strong><%= @listing_decorator.name %></strong></h4>
    <p><%= number_to_currency(@listing_decorator.price) %>   <small><%= @listing_decorator.display_in_stock %></small></p>
    <%= @listing_decorator.description %>
    <br/><br/>
    <div class="star-rating" data-score= <%= @avg_rating %> ></div> 
    <%= "#{@reviews.length} reviews" %> 
    <% if current_user != @listing.user %>
    <% if @listing_decorator.in_stock? %>
    <br/>
    <div class="center">
<!--      
      <%= link_to "Buy It Now", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
-->
      <%= link_to new_listing_order_path(@listing), class: "btn btn-primary active", data: { no_turbolink: true }  do %>
          <i class="glyphicon glyphicon-shopping-cart"></i> Buy It Now
      <% end %>
    </div>
    <% end %>
    <br/>    
    <div class="center">
      <%= link_to new_listing_review_path(@listing), class: "btn btn-primary active", data: { no_turbolink: true }  do %> 
          <i class="glyphicon glyphicon-plus"></i> New Review
      <% end %>
    </div>
    <% if @reviews.blank? %>
    <br/>
    No reviews yet. Be the first to write one!
    <% end %>
    <% end %>    
    
    <% if @reviews.any? %>
      <br/><br/>
      <p><strong>The latest 5 reviews:</strong></p>
      <table class="table">
        <thead>
          <tr>
            <th class="col-md-3">Reviewed By</th>
            <th class="col-md-9">Rating & Comments</th>
          </tr>
        </thead>
        <tbody>
          <% @reviews = @reviews.limit(5) %>
          <% @reviews.each do |review| %>
          <tr>
            <td>
              <strong><%= "#{review.user.name}" %></strong><br/>
              on <%= review.created_at.strftime("%-m/%-d/%-y") %>
              <br/>
              <%= timeago(review.created_at) %>
            </td>            
            <td>
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <br/>
              <%= h(review.comment).gsub(/\n/, '<br/>').html_safe %>
              <br/>
              <% if user_signed_in? %>
                <% if (review.user == current_user) || (current_user.admin?) %>
                  <%= link_to "Edit", edit_listing_review_path(@listing, review), class: "btn btn-link" %>
                  <%= link_to "Delete", listing_review_path(@listing, review), method: :delete, class: "btn btn-link"%>
                <% end %>
              <% end %>              
            </td>
          </tr>
          <% end %>
        </tbody>
    </table>    
    <% end %>
    
  </div>
</div>

<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

<script>
  <% if Rails.env.development? %>
  $('.star-rating').raty({
    path: '/assets',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
  <% else %>
  $('.star-rating').raty({
    path: 'https://s3.amazonaws.com/setsy/images',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
    
  <% end %>  
</script>