config/routes.rb
Rails.application.routes.draw do
  

  

  resources :users, only: [:index, :edit, :update]
  get 'recipient' => "users#recipient"
  patch 'update_recipient' => "users#update_recipient"
  
  resources :categories
  
  devise_for :users
  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create]
    resources :reviews, except: [:show, :index]
  end
  get 'orders/:id' => "orders#receipt", as: :receipt
  get 'pages/about'

  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  
  root 'listings#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :timeout_in => 15.minutes
  
  validates :name, presence: true
  
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
  has_many :reviews, dependent: :destroy
  
  scope :recent, -> { order(created_at: :desc) }
  scope :excluding_user_by_email, -> (user_email) { where.not(email: user_email) }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  before_action :set_user_recipient, only: [:recipient, :update_recipient]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.excluding_user_by_email(current_user.email).recent.paginate(pagination_size(Paginable::USER_SIZE_MAX_PAGE))
  end


  # GET /users/1/edit
  def edit
  end


  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path }
      else
        format.html { render :edit }
      end
    end
  end

  # GET /recipient
  def recipient    
  end


  # PATCH/PUT /update_recipient
  # PATCH/PUT /users/1.json
  def update_recipient
    stripe_service = StripeService.new
    recipient = stripe_service.create_recipient(params[:stripeToken], current_user.name, flash)
    @user.recipient = recipient.id
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to listings_path }
      else
        format.html { render :recipient }
      end
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :admin, :country, :routing_number, :account_number)
    end
  
    def set_user_recipient
      @user = current_user
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, html: {id: 'set_admin_role'}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :user %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :admin, class: "form-control", :autofocus => true %> <%= f.label "Set to admin role" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/users/_recipientform.html.erb
<%= form_for(@user, url: update_recipient_path, html: {id: 'new_recipient', method: :patch}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>      
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
  <br>

  <div class="form-group">
    <%= label_tag :country %>
    <%= text_field_tag :country, nil, { :placeholder => 'US', :name => nil, :'data-stripe' => "country", class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= label_tag :routing_number %>
    <%= text_field_tag :routing_number, nil,  { :placeholder => '111000025', :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= label_tag :account_number %>
    <%= text_field_tag :account_number, nil,  { :placeholder => '000123456789', :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', users_path, class: "btn btn-link" %>

app/views/users/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="center">User</th>
      <th class="center">Is admin role?</th>
      <th class="center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>  
        <td><div class="center"><%= user.admin %></div></td>
        <td>
          <div class="center">
            <%= link_to 'Set user admin role', edit_user_path(user), class: "btn btn-link" %>
          </div>  
        </td> 
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<div class="center">
  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>
<br/>

app/views/users/recipient.html.erb
<h1>Bank Account Information</h1>

<%= render 'recipientform' %>