config/routes.rb
Rails.application.routes.draw do
  

  

  resources :users, only: [:index, :edit, :update]
  get 'recipient' => "users#recipient"
  patch 'update_recipient' => "users#update_recipient"
  
  resources :categories
  
  devise_for :users
  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create]
    resources :reviews, except: [:show, :index]
  end
  get 'orders/:id' => "orders#receipt", as: :receipt
  get 'pages/about'

  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  
  root 'listings#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :category, presence: true 
  validates_uniqueness_of :category, message: "%{value} already exists."
  has_many :listings
  
  scope :recent, -> { order(created_at: :desc) }
  scope :active, -> { where(active: true) }
  scope :sorted, -> { order(:category) }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.recent.paginate(pagination_size(Paginable::CATEGORY_SIZE_MAX_PAGE))
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        #format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.html { redirect_to categories_path }        
#        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
#        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        #format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.html { redirect_to categories_path }
#        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
#        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
#      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category, :active)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>           
      <h4><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h4>
      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.text_field :category, autofocus: true, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.check_box :active %> <%= f.label "Active" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

<!-- <%= link_to 'Show', @category, class: "btn btn-link"%> | -->
<%= link_to 'Back', categories_path, class: "btn btn-link" %>

app/views/categories/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th class="center">Category</th>
      <th class="center">Status</th>
      <th class="center">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.category %></td>               
        <td class="center"><%= category.active %></td>               
        <td>
          <div class="center">
          <!-- <%= link_to 'Show', category, class: "btn btn-link" %> | -->
          <%= link_to 'Edit', edit_category_path(category), class: "btn btn-link" %>
          </div>  
        </td> 
        <!--
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br/>
<div class="center">
  <%= will_paginate @categories, renderer: BootstrapPagination::Rails %>
</div>
<br>
  <%= link_to new_category_path, class: "btn btn-primary", data: { no_turbolink: true } do %>
    <i class="glyphicon glyphicon-plus"></i> New Category
  <% end %>

app/views/categories/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', categories_path, class: "btn btn-link" %>