config/routes.rb
Rails.application.routes.draw do
  

  

  resources :users, only: [:index, :edit, :update]
  get 'recipient' => "users#recipient"
  patch 'update_recipient' => "users#update_recipient"
  
  resources :categories
  
  devise_for :users
  resources :listings do
    collection do
      get 'search'
    end
    resources :orders, only: [:new, :create]
    resources :reviews, except: [:show, :index]
  end
  get 'orders/:id' => "orders#receipt", as: :receipt
  get 'pages/about'

  get 'pages/contact'
  get 'seller' => "listings#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"
  
  root 'listings#index'

end

app/views/layouts/_footer.html.erb
<br/>
<div class="center">
  <p><strong>Copyright <i class="glyphicon glyphicon-copyright-mark"></i> 2018 SEtsy</strong> by <strong>Daniel Ha</strong><br/>
    <strong>Powered by</strong><br/> 
    <strong>Rails <%= Rails::VERSION::STRING %>, Bootstrap 3.2.0 and Stripe <%= Gem.loaded_specs["stripe"].version.to_s %></strong></p>
  <%= social_share_button_tag("SEtsy", :url => "http://setsy.herokuapp.com") %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">SEtsy</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    
    <ul class="nav navbar-nav">
      
      <li><%= link_to "About", pages_about_path %></li>
      <!--
      <li><%= link_to "Contact", pages_contact_path %></l>
      -->
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <% Category.active.sorted.each do |cat| %>
          <li><%= link_to cat.category, listings_path(category: cat.category)  %></li>
          <% end %>
        </ul>
      </li>
      <%= form_tag search_listings_path, method: :get, class: "navbar-form navbar-left" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
      
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
      <% if current_user.admin? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin Settings <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to categories_path do %>
              <i class="glyphicon glyphicon-book"></i> Manage Categories
              <% end %>              
            </li>
            <li><%= link_to users_path do %>
              <i class="glyphicon glyphicon-user"></i> Set Admin Role
              <% end %>              
            </li>
          </ul>
        </li>
      <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Seller Account <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to seller_path do %>
              <i class="glyphicon glyphicon-book"></i> Manage Listings
              <% end %>             
            </li>
            <li><%= link_to sales_path do %>
              <i class="glyphicon glyphicon-header"></i> Sales History
              <% end %>              
            </li>
            <% if current_user.recipient.blank? %>
            <li><%= link_to recipient_path, data: { no_turbolink: true } do %>
              <i class="glyphicon glyphicon-bank"></i> Set Bank Recipient
              <% end %>              
            </li>
            <% end %>
          </ul>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to purchases_path do %>
              <i class="glyphicon glyphicon-header"></i> Purchase History
              <% end %>
              
            </li>
            <li><%= link_to edit_user_registration_path do %>
              <i class="glyphicon glyphicon-edit"></i> Edit Profile
              <% end %>
              
            </li>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
              <i class="glyphicon glyphicon-log-out"></i> Sign Out
              <% end %>
            </li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to new_user_registration_path do %>
              <i class="glyphicon glyphicon-user"></i> Sign Up
            <% end %>
        </li>
        <li><%= link_to  new_user_session_path do %>
              <i class="glyphicon glyphicon-log-in"></i> Login In
            <% end %>
        </li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Etsyapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  </div>
  
  <%= javascript_tag do %>
     $(function() {
       $("time.timeago").timeago();
     });
  <% end %>  
</body>
</html>